backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

locale: ja

collections:
  - name: "photos"
    label: "写真管理"
    files:
      - label: "写真データ"
        name: "photos"
        file: "content/photos.json"
        fields:
          - {label: "打合せ内容", name: "打合せ", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "建築部位名称", name: "部位名称", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "テイスト", name: "テイスト", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "収納", name: "収納", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "照明", name: "照明", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "標準機器", name: "標準機器", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "インターネット", name: "インターネット", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "カーテン", name: "カーテン", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "洗面", name: "洗面", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "家具", name: "家具", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "仕上げ", name: "仕上げ", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "給湯器", name: "給湯器", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "暖房", name: "暖房", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "ペット", name: "ペット", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "選木", name: "選木", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "住まいの工夫", name: "コロナ", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
          - {label: "植栽", name: "植栽", widget: list, fields: [{label: "写真", name: src, widget: image}, {label: "キャプション", name: caption, widget: string, required: false}]}
